(() => {
  'use strict';

  const STORAGE_KEY = 'wjc-bar-v1';
  const baseIngredients = [
    { id:'ember', name:'琥珀糖浆', symbol:'◐', note:'焦糖 · 温热', color:'#b97753', tags:['甜','暖'], moods:['comfort','celebrate'] },
    { id:'blue', name:'雨后蓝莓', symbol:'●', note:'微酸 · 深色', color:'#526b83', tags:['酸','果香'], moods:['reflect','missing'] },
    { id:'tea', name:'晚风乌龙', symbol:'〰', note:'茶感 · 清醒', color:'#87976e', tags:['清','木质'], moods:['reflect','begin'] },
    { id:'pear', name:'白梨露', symbol:'◇', note:'清甜 · 柔软', color:'#b9a878', tags:['甜','轻盈'], moods:['comfort','begin'] },
    { id:'smoke', name:'壁炉烟盐', symbol:'✦', note:'烟熏 · 咸感', color:'#8e6e62', tags:['烟熏','复杂'], moods:['missing','reflect'] },
    { id:'citrus', name:'月光柑橘', symbol:'☼', note:'明亮 · 清新', color:'#d59b57', tags:['酸','明亮'], moods:['celebrate','begin'] },
    { id:'cocoa', name:'深夜可可', symbol:'●', note:'苦甜 · 厚实', color:'#785447', tags:['苦甜','厚实'], moods:['comfort','missing'] },
    { id:'herb', name:'窗台香草', symbol:'⌁', note:'青草 · 回甘', color:'#6f8b72', tags:['草本','回甘'], moods:['begin','celebrate'] },
    { id:'ginger', name:'暖姜汽泡', symbol:'♢', note:'辛香 · 跳动', color:'#c28a56', tags:['辛香','明亮'], moods:['celebrate','comfort'] },
    { id:'plum', name:'晚熟李子', symbol:'●', note:'果熟 · 深红', color:'#764c61', tags:['果熟','深红'], moods:['missing','comfort'] },
    { id:'soda', name:'雾白气泡', symbol:'·', note:'轻盈 · 清脆', color:'#a7b8b3', tags:['气泡','清脆'], moods:['begin','celebrate'] },
    { id:'saltleaf', name:'海边盐叶', symbol:'≈', note:'矿物 · 海风', color:'#718b87', tags:['矿物','海风'], moods:['missing','reflect'] }
  ];
  const techniques = [{id:'stir',name:'慢慢搅拌'},{id:'shake',name:'摇和醒香'},{id:'layer',name:'分层呈现'},{id:'ice',name:'大冰安静降温'}];
  const glasses = [{id:'low',name:'矮杯'},{id:'high',name:'长饮杯'},{id:'tea',name:'茶盏'},{id:'coupe',name:'月牙杯'}];
  const garnishes = [{id:'orange',name:'柑橘皮'},{id:'leaf',name:'香草叶'},{id:'star',name:'糖星'},{id:'none',name:'不加装饰'}];
  const guests = [
    {id:'lin',name:'林弦',role:'把话收回去的人',avatar:'林',avatarClass:'avatar-lin',status:'已来过 2 次',mood:'reflect',chapter:1,story:'她把伞放在门口，坐在窗边最暗的那张桌子。手机亮了又灭，像是有人在等她先开口。',line:'“今天不想说近况。你这里还有那种……喝完不会立刻想起答案的东西吗？”',clues:['避开窗外的灯','指尖在杯垫上画圈','旧唱片停在 B 面'],history:'上次她带走了《不急着天晴》，三天后寄来一张没有署名的明信片。',result:'她没有讲完那件事，但临走时把手机调成了静音。门铃响过之后，窗边那盏灯多亮了一会儿。'},
    {id:'mori',name:'莫里',role:'把每件事都修好的人',avatar:'莫',avatarClass:'avatar-mori',status:'第一次来',mood:'comfort',chapter:1,story:'他带着一盒没有修好的旧收音机进门，先向每一张桌子道歉，最后才坐下。袖口沾着机油。',line:'“我不太会休息。要是我坐在这里，你可以假装没有看见我吗？”',clues:['手掌有细小划痕','把椅子摆得很正','听见音乐会抬头'],history:'你还不认识他。收音机里偶尔传出半句天气预报。',result:'他终于把收音机放下，喝完后问你明天几点开门。那不是催促，是在为自己留下一个去处。'},
    {id:'yu',name:'余照',role:'把告别说得很轻的人',avatar:'余',avatarClass:'avatar-yu',status:'已来过 1 次',mood:'missing',chapter:2,story:'她穿着一件不合季节的亚麻外套，给吧台上每一个空杯子都点了点头。她似乎刚从很远的地方回来。',line:'“有没有一种味道，像是还没来得及说再见，但已经知道不会再见了？”',clues:['行李牌没有撕','只看不喝水','问起唱片的主人'],history:'上次她留下了一枚生锈的车票，压在《北岸晚钟》的菜单下。',result:'她没有带走饮品。她说有些东西不适合离开酒馆，并把车票翻了个面。'},
    {id:'shen',name:'沈岸',role:'把热闹带进安静里的人',avatar:'沈',avatarClass:'avatar-shen',status:'今晚可能出现',mood:'celebrate',chapter:1,story:'他在门外打了三个电话才进来，进门后却把声音调得很低。胸前别着一枚今天刚收到的铜色徽章。',line:'“我有件开心事。但我不想把它庆祝得像完成了一项任务。”',clues:['笑得很慢','把徽章藏起来','想听一点有节奏的音乐'],history:'他还没和你说过话，但每次路过都会看一眼门上的营业时间。',result:'他把那枚徽章留在吧台边，说明天会带一个人来。那一晚，酒馆第一次有人轻轻鼓掌。'},
    {id:'qiao',name:'乔安',role:'把自己藏在玩笑里的人',avatar:'乔',avatarClass:'avatar-qiao',status:'已来过 3 次',mood:'begin',chapter:3,story:'她比约定时间早到了半小时，坐在门口写一张很长的清单。看见你时，她把清单折起来，说只是购物计划。',line:'“我打算下个月离开这座城。你觉得，一个人重新开始时，应该带走什么？”',clues:['清单写了又划掉','鞋尖朝向门外','记得每次的杯型'],history:'她已经把你的三杯作品写进自己的小册子，却始终没有给它们命名。',result:'她带走了一页你写下的材料表。后来你收到一封信，说她在新城市开了一扇朝西的窗。'},
  ];
  const baseRecipes = [
    {id:'r1',name:'不急着天晴',desc:'乌龙的清醒托住蓝莓的酸，像有人陪你看完一场雨。',tags:['清爽','微酸','木质'],signature:true,color:'#526b83',mix:{ingredients:['blue','tea'],technique:'stir',sweet:35,acid:63,temp:54,intensity:30,glass:'high',garnish:'orange'}},
    {id:'r2',name:'壁炉边的回声',desc:'琥珀糖浆和烟盐在矮杯里慢慢靠近，适合不必解释的晚上。',tags:['温热','烟熏','厚实'],signature:true,color:'#9d634d',mix:{ingredients:['ember','smoke','cocoa'],technique:'stir',sweet:67,acid:18,temp:25,intensity:62,glass:'low',garnish:'star'}},
    {id:'r3',name:'把月亮放低',desc:'白梨露和柑橘的光，不打扰任何人，却让桌面亮了一点。',tags:['轻盈','明亮','柔软'],signature:false,color:'#b99f67',mix:{ingredients:['pear','citrus'],technique:'shake',sweet:59,acid:55,temp:62,intensity:22,glass:'coupe',garnish:'orange'}},
    {id:'r4',name:'北岸晚钟',desc:'一杯带着车站气味的深色饮品，余味比想象中更长。',tags:['深色','回甘','低声'],signature:true,color:'#6b5260',mix:{ingredients:['blue','smoke','herb'],technique:'layer',sweet:28,acid:43,temp:45,intensity:72,glass:'tea',garnish:'leaf'}},
    {id:'r5',name:'明天也开门',desc:'窗台香草落在清甜的白梨里，给还没发生的事留一个位置。',tags:['草本','清甜','新开始'],signature:false,color:'#758b70',mix:{ingredients:['pear','tea','herb'],technique:'ice',sweet:54,acid:34,temp:79,intensity:24,glass:'high',garnish:'leaf'}},
    {id:'r6',name:'收音机里的晴天',desc:'暖姜汽泡和雾白气泡把旧频道重新点亮，适合慢慢学会休息。',tags:['辛香','气泡','轻快'],signature:false,color:'#b98759',mix:{ingredients:['ginger','soda','citrus'],technique:'shake',sweet:48,acid:61,temp:71,intensity:29,glass:'high',garnish:'orange'}},
    {id:'r7',name:'不寄出的车票',desc:'晚熟李子的深红落在海边盐叶里，像一段被折好却没有寄出的旅程。',tags:['深红','矿物','长余味'],signature:true,color:'#704b5d',mix:{ingredients:['plum','saltleaf','smoke'],technique:'layer',sweet:42,acid:37,temp:47,intensity:58,glass:'coupe',garnish:'leaf'}},
    {id:'r8',name:'铜灯下的笑声',desc:'柑橘、暖姜和琥珀糖浆在杯沿碰了一下，不把开心庆祝成任务。',tags:['温暖','辛香','明亮'],signature:false,color:'#c18454',mix:{ingredients:['citrus','ginger','ember'],technique:'shake',sweet:65,acid:50,temp:43,intensity:46,glass:'low',garnish:'orange'}},
    {id:'r9',name:'一半留给海',desc:'白梨的柔软遇见盐叶的风，喝到最后，桌面上只剩一小圈水痕。',tags:['柔软','海风','安静'],signature:true,color:'#849f9b',mix:{ingredients:['pear','saltleaf','soda'],technique:'ice',sweet:47,acid:31,temp:82,intensity:21,glass:'tea',garnish:'none'}},
    {id:'r10',name:'门口的第二把伞',desc:'李子、蓝莓和窗台香草组成一把不太对称的伞，替两个人挡一会儿雨。',tags:['果熟','草本','陪伴'],signature:false,color:'#70576a',mix:{ingredients:['plum','blue','herb'],technique:'stir',sweet:46,acid:56,temp:52,intensity:39,glass:'low',garnish:'star'}},
  ];
  const quotes = ['有些夜晚，不需要被解决，只需要被认真度过。','好味道不是答案，是允许人继续想一会儿。','灯亮着，门就不算关上。','今天的雨，替很多人说了不想说的话。'];
  const dialogueBook = {
    lin:{arc:'悲伤后的放下',openings:['“今天不想说近况。你这里还有那种……喝完不会立刻想起答案的东西吗？”','“那张明信片我收到了。没有署名，所以我可以假装它来自任何人。”','“我好像终于可以说了：那天之后，我没有再回那条消息。”'],replies:[['她把手收回袖口：“那就先不说答案。你这里的灯，今晚比上次近一点。”','她看了看杯子：“谢谢你没有把沉默也解释成一种问题。”','她笑了一下：“你总能把一句话说得像一张空白的椅子。”'],['她把明信片翻过来：“我以为自己在等一个解释，后来发现只是在等自己不再等。”','她摸了摸纸边：“没有名字的东西，有时反而比较诚实。”','她说：“如果我把它放进日志里，你会替我保密吗？”'],['她的肩膀落下来：“原来放下不是不难过，是不用再回去证明自己难过。”','她看着窗上的水痕：“我现在可以讲完了，但今晚先不讲。”','她把杯子推近一点：“我想把这杯喝完，再回家。”']],followups:[['把一小碟温水放在她手边。','问起那张明信片，而不是那条消息。','陪她听完唱片的 B 面。'],['告诉她：日志会替她记住，不必现在回答。','把纸巾折成一只很小的船。','说起你最近一次没有回复的消息。'],['不追问，把窗边的灯调暗一格。','请她为这杯饮品写下一个名字。','把门口的伞递给她。']],endings:['那晚她没有讲完，但把杯子留在了桌上，像是给明天留了一个位置。','她把明信片压在菜单下，说下次来时想看看它有没有长出名字。','她喝到最后一口，终于把手机调成了静音。门铃响过之后，窗边那盏灯多亮了一会儿。']},
    mori:{arc:'争吵后的宁静',openings:['“我不太会休息。要是我坐在这里，你可以假装没有看见我吗？”','“我和弟弟吵了一架。收音机没坏，是我不想听见它响。”','“他今天把修好的收音机拿走了，却没有说谢谢。奇怪的是，我没有追出去。”'],replies:[['他把手掌摊开：“你可以看见我，但不用马上帮我修好。”','他点点头：“那我就坐在这里。被看见也不一定要做些什么。”','他听着冰块碰杯：“原来有人假装没看见，也是一种体谅。”'],['他苦笑：“我们都在抢着证明自己有道理，没人记得要把门关轻一点。”','他看着收音机：“吵架之后房间很安静，安静得像一件还没修好的东西。”','他把机油味的袖口卷起来：“我想让它安静一会儿，不是永远安静。”'],['他第一次没有道歉：“我还没学会不靠一句谢谢确认自己有用。”','他轻声说：“他下次可能还会吵，但我不用每次都带着工具箱去。”','他笑了：“收音机在他那里也好。它终于不用替我留住什么。”']],followups:[['把杯垫摆正，但不替他摆椅子。','问他想听哪一段频道。','把调酒器放下，和他一起安静十秒。'],['给收音机留一块干净的桌面。','告诉他：修理和和好不是同一件事。','放一首没有歌词的唱片。'],['问他要不要带走一小包窗台香草。','把“谢谢”换成“你辛苦了”。','陪他听听收音机里下一句天气预报。']],endings:['他喝完后把收音机放下，问你明天几点开门。那不是催促，是在为自己留下一个去处。','争吵没有被抹掉，但它终于有了一个不必继续扩大的夜晚。','他把收音机带回去，临出门时说：“下次我可以只来坐坐。”']},
    yu:{arc:'悲伤后的放下',openings:['“有没有一种味道，像是还没来得及说再见，但已经知道不会再见了？”','“那张车票不是我的。我只是替它坐过一站。”','“我今天不赶车了。你这里还有靠近海边的味道吗？”'],replies:[['她看着杯沿：“如果它不催我想起谁，也许我可以试一口。”','她把手放在桌上：“你不用替我找一个好听的告别。”','她问：“这里的灯，会在客人走后继续亮吗？”'],['她把车票翻到背面：“原来空白也能是一种到站。”','她说：“我一直把车票留着，好像这样那个人就还在下一站。”','她笑得很轻：“现在我想把它留给一个不认识的人。”'],['她闭上眼：“海边的味道不是咸，是风把很多话带走之后剩下的空。”','她说：“我想坐到唱片结束，再决定要不要走。”','她把外套搭在椅背上：“今晚我不需要行李牌。”']],followups:[['让她自己决定是否加一片柑橘皮。','把车票放到灯下，不问它来自哪里。','问她要不要让这杯保持无名。'],['给她一只空信封。','说：有些告别可以不寄出。','把菜单翻到没有写字的那一页。'],['把窗户留一条缝。','陪她把车站的声音换成雨声。','告诉她下次来，窗边还会有位置。']],endings:['她没有带走饮品。她说有些东西不适合离开酒馆，并把车票翻了个面。','她把车票留在吧台边，像把一段路交还给它自己。','她喝完后起身，没有说再见，只说：“这次我知道怎么回家了。”']},
    shen:{arc:'快乐后的治愈',openings:['“我有件开心事。但我不想把它庆祝得像完成了一项任务。”','“今天有人为我鼓掌，我第一反应是躲到最后一排。”','“我把那枚徽章带来了。你不用夸它，我只是想让它也坐一会儿。”'],replies:[['他把徽章藏到杯垫下：“开心也可以小声一点，对吧？”','他笑起来：“原来被祝贺之后，不一定要立刻变得更厉害。”','他说：“我想把这件事分给一张桌子，而不是分给所有人。”'],['他揉了揉耳朵：“掌声停下来以后，我才听见自己真的很累。”','他把杯子转了一圈：“我不是不开心，只是不知道开心以后要做什么。”','他问：“你会不会也有那种，值得庆祝但只想回家的日子？”'],['他把徽章放在灯下：“现在看它，我不会觉得它在催我继续。”','他轻轻碰杯：“我可以带一个人来这里吗？她会把音乐听得很认真。”','他笑着说：“原来好的消息不用马上长成新的计划。”']],followups:[['把音乐调得有一点节奏，但不要变成舞台。','给他一只空杯垫，允许他把徽章放下。','举杯说“今天先到这里”。'],['把灯光调亮一格。','问他最想把这件事告诉谁。','替他把掌声改成一次很轻的碰杯。'],['在日志里留一行空白。','告诉他明天也可以只是普通的一天。','为下一位客人预留一张桌子。']],endings:['他把那枚徽章留在吧台边，说明天会带一个人来。那一晚，酒馆第一次有人轻轻鼓掌。','他没有急着离开，直到唱片结束才说：“今天的开心终于有地方放了。”','他走出门又回头：“我下次会把她带来，但今晚我想先记住这个安静。”']},
    qiao:{arc:'告别后的继续',openings:['“我打算下个月离开这座城。你觉得，一个人重新开始时，应该带走什么？”','“清单删到只剩三样东西了，但我还是觉得太多。”','“我找到新城市的房子了。窗户朝西，下午会有很亮的光。”'],replies:[['她把清单折起来：“我怕带走太多，就会没有地方装新的东西。”','她说：“你每次都不问我会不会回来。谢谢。”','她看着门外：“也许重新开始不是换一个人，而是换一种走路的速度。”'],['她划掉一行：“我本来想带走所有证明自己来过的东西。”','她把笔递给你：“如果只能留一样，你会留什么？”','她笑：“清单最奇怪的地方，是它会让舍不得看起来像计划。”'],['她靠着椅背：“西边的光会不会让人更容易记得黄昏？”','她说：“我给那扇窗留了一把空椅子。”','她把一页材料表放进包里：“这不是纪念品，是我想知道新的地方有没有自己的味道。”']],followups:[['请她为今晚选一杯新名字。','在菜单背面写一行“带走什么都可以”。','问她希望新窗边先看见什么。'],['把你的材料表给她，但不替她选择。','说：舍不得也可以打包。','请她把清单留一项给明天。'],['为她调一杯适合下午的饮品。','把窗边的椅子轻轻移向西面。','告诉她，回来时可以不用提前预约。']],endings:['她带走了一页你写下的材料表。后来你收到一封信，说她在新城市开了一扇朝西的窗。','她没有把清单带走，只把最后一项改成了“允许自己改变主意”。','她把新地址写在菜单角落，没有说一定会回来，但把门铃声记得很清楚。']}
  };

  const defaultState = {
    view:'home', selectedGuest:'lin', guestVisits:{lin:0,mori:0,yu:0,shen:0,qiao:0}, served:0, logs:[], recipes:baseRecipes, signatures:[], atmosphere:'rain', freeMode:false, sound:false, mix:{name:'',ingredients:[],technique:'stir',sweet:52,acid:48,temp:40,intensity:35,glass:'low',garnish:'orange'}, recipeCounter:1, menuFilter:'all'
  };
  let state = loadState();
  let serviceDraft = null;
  const $ = (selector) => document.querySelector(selector);
  const $$ = (selector) => [...document.querySelectorAll(selector)];
  function loadState(){ try { const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}'); const savedRecipes=Array.isArray(saved.recipes)?saved.recipes:[]; const savedIds=new Set(savedRecipes.map(recipe=>recipe.id)); return {...defaultState,...saved,recipes:[...baseRecipes.filter(recipe=>!savedIds.has(recipe.id)),...savedRecipes]}; } catch { return {...defaultState}; } }
  function saveState(){ localStorage.setItem(STORAGE_KEY,JSON.stringify(state)); }
  function escapeHtml(value){ return String(value).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c])); }
  function guest(){ return guests.find(g=>g.id===state.selectedGuest)||guests[0]; }
  function sceneFor(g){ return dialogueBook[g.id]||dialogueBook.lin; }
  function visitIndexFor(g){ return Math.min(state.guestVisits[g.id]||0,2); }
  function guestOpening(g){ const scene=sceneFor(g); return scene.openings[visitIndexFor(g)]||scene.openings[0]; }
  function guestStatus(g){ const visits=state.guestVisits[g.id]||0; return visits?`来过 ${visits} 次`:'还没坐下'; }
  function currentDrinkName(){ return $('#recipe-name')?.value.trim()||state.mix.name||mixTitle(); }
  function conversationChoices(g){ return [`先问一句普通的近况：“今天过得怎么样？”`,`把杯子推过去，不急着给建议。`,`告诉${g.name}：这杯没有名字，你可以自己决定它叫什么。`]; }
  function notify(message){ const toast=$('#toast'); toast.textContent=message;toast.classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>toast.classList.remove('show'),2600); }
  function setView(view){ state.view=view; saveState(); $$('.view').forEach(el=>el.classList.toggle('active-view',el.id===`view-${view}`)); $$('.nav-item').forEach(el=>el.classList.toggle('active',el.dataset.view===view)); if(view==='guests')renderGuests(); if(view==='lab')renderLab(); if(view==='menu')renderMenu(); if(view==='journal')renderJournal(); window.scrollTo({top:0,behavior:'smooth'}); }
  function renderIngredients(){ $('#ingredient-grid').innerHTML=baseIngredients.map(i=>`<button class="ingredient-button ${state.mix.ingredients.includes(i.id)?'selected':''}" data-ingredient="${i.id}"><span class="ingredient-symbol" style="color:${i.color}">${i.symbol}</span><strong>${i.name}</strong><small>${i.note}</small></button>`).join(''); }
  function renderLab(){ renderIngredients(); $('#technique-row').innerHTML=techniques.map(t=>`<button class="technique-button ${state.mix.technique===t.id?'selected':''}" data-technique="${t.id}">${t.name}</button>`).join(''); $('#glass-row').innerHTML=glasses.map(g=>`<button class="choice-button ${state.mix.glass===g.id?'selected':''}" data-glass="${g.id}">${g.name}</button>`).join(''); $('#garnish-row').innerHTML=garnishes.map(g=>`<button class="choice-button ${state.mix.garnish===g.id?'selected':''}" data-garnish="${g.id}">${g.name}</button>`).join(''); $('#free-mode-toggle').checked=state.freeMode; $('#recipe-name').value=state.mix.name||''; $('#preview-context').textContent=state.freeMode?'自由实验':`为 ${guest().name} 调制`; renderSliders(); updatePreview(); updateGuestPrompt(); }
  function renderSliders(){ const fields=[['sweet','甜度'],['acid','酸度'],['temp','温度'],['intensity','浓度']]; $('#flavor-sliders').innerHTML=fields.map(([key,label])=>`<div class="slider-row"><label>${label}</label><input type="range" min="0" max="100" value="${state.mix[key]}" data-flavor="${key}" /><output>${state.mix[key]}%</output></div>`).join(''); }
  function colorForMix(){ const chosen=state.mix.ingredients.map(id=>baseIngredients.find(i=>i.id===id)).filter(Boolean); if(!chosen.length)return '#8e5a4d'; const rgb=chosen.reduce((acc,item)=>{const hex=item.color.replace('#','');return acc.concat([parseInt(hex.slice(0,2),16),parseInt(hex.slice(2,4),16),parseInt(hex.slice(4,6),16)]);},[]); const avg=[0,1,2].map(i=>Math.round(rgb.filter((_,n)=>n%3===i).reduce((a,b)=>a+b,0)/chosen.length)); return `rgb(${avg.join(',')})`; }
  function mixTitle(){ const chosen=state.mix.ingredients.map(id=>baseIngredients.find(i=>i.id===id)).filter(Boolean); if(!chosen.length)return '还没有名字的夜晚'; const names=['微光','慢潮','小小的回声','窗边第七盏灯','雨停之后']; return names[(state.mix.ingredients.length+state.mix.sweet+state.mix.acid)%names.length]; }
  function updatePreview(){ const chosen=state.mix.ingredients.map(id=>baseIngredients.find(i=>i.id===id)).filter(Boolean); const tags=[...new Set(chosen.flatMap(i=>i.tags))].slice(0,3); const typedName=$('#recipe-name')?.value.trim()||state.mix.name; $('#drink-title').textContent=typedName||mixTitle(); $('#drink-description').textContent=chosen.length?`${chosen.map(i=>i.name).join('、')}，用${techniques.find(t=>t.id===state.mix.technique)?.name}把今晚的语气放进杯子。`:'从左边挑一些材料。每一次犹豫，都会留下不同的味道。'; $('#drink-tags').innerHTML=tags.map(t=>`<span>${t}</span>`).join(''); $('#drink-glass').className=`drink-glass glass-${state.mix.glass||'low'}`; $('#liquid').style.background=`linear-gradient(90deg,${colorForMix()},#d49a65aa 53%,${colorForMix()})`; $('#garnish-float').textContent=garnishes.find(g=>g.id===state.mix.garnish)?.name==='不加装饰'?'':({orange:'◒',leaf:'⌁',star:'✦'}[state.mix.garnish]||'✦'); $('#flavor-bars').innerHTML=[['甜',state.mix.sweet],['酸',state.mix.acid],['温',100-state.mix.temp],['烈',state.mix.intensity]].map(([l,v])=>`<div class="flavor-meter"><i><span style="width:${v}%"></span></i><label>${l}</label></div>`).join(''); }
  function updateGuestPrompt(){ const prompt=$('#guest-prompt'); prompt.style.display=state.freeMode?'none':'flex'; }
  function renderAtmosphere(){ const choices=[['rain','◌','安静雨夜','窗景 · 低音量'],['retro','◉','复古唱片','铜灯 · Side B'],['green','♧','自然呼吸','植物 · 木香'],['radio','⌁','深夜电台','蓝光 · 慢谈']]; $('#atmosphere-choices').innerHTML=choices.map(([id,symbol,name,note])=>`<button class="atmosphere-choice ${state.atmosphere===id?'selected':''}" data-atmosphere="${id}"><span class="atmo-symbol">${symbol}</span><strong>${name}</strong><small>${note}</small></button>`).join(''); document.body.classList.remove('atmo-rain','atmo-retro','atmo-green','atmo-radio'); document.body.classList.add(`atmo-${state.atmosphere}`); }
  function renderGuests(){ const selected=guest(); const scene=sceneFor(selected); $('#guest-list').innerHTML=guests.map(g=>`<button class="guest-card ${g.id===selected.id?'selected':''}" data-guest="${g.id}"><div class="avatar ${g.avatarClass}">${g.avatar}</div><div><h3>${g.name}</h3><p>${g.role}</p></div><span class="guest-status">${guestStatus(g)}</span></button>`).join(''); const progress=Math.min(100,(state.guestVisits[selected.id]||0)*34+18); $('#guest-detail').innerHTML=`<div class="detail-top"><div class="avatar ${selected.avatarClass}">${selected.avatar}</div><div><h3>${selected.name}</h3><div class="guest-meta">${selected.role} · ${scene.arc} · 关系进度 ${Math.min(3,(state.guestVisits[selected.id]||0)+1)} / 3</div></div></div><p class="detail-story">${selected.story}</p><div class="clue-row">${selected.clues.map(c=>`<span class="clue">${c}</span>`).join('')}<span class="clue mood-clue">${scene.arc}</span></div><p class="detail-story" style="font-size:13px;color:#9d9189;margin:0 0 23px"><em>她 / 他低声说：</em> ${guestOpening(selected)}</p><div class="detail-actions"><button class="primary-button" data-start-service="${selected.id}">为 ${selected.name} 调一杯 <span>→</span></button><button class="secondary-button" data-view="lab">去自由实验室</button></div><div class="detail-footnote">${selected.history}</div><div class="detail-progress"><span style="width:${progress}%"></span></div>`; }
  function renderMenu(){ const filter=state.menuFilter; let items=state.recipes.length?state.recipes:[]; if(filter==='signature')items=items.filter(r=>r.signature); if(filter==='archive')items=items.filter(r=>!r.signature); const grid=$('#menu-grid'); grid.innerHTML=items.length?items.map(r=>`<article class="menu-card"><span class="menu-card-sign">${r.signature?'✦ SIGNATURE':'CREATION LOG'}</span><h3>${escapeHtml(r.name)}</h3><p>${escapeHtml(r.desc)}</p><div class="drink-tags">${r.tags.map(t=>`<span>${escapeHtml(t)}</span>`).join('')}</div><button class="edit-recipe" data-edit-recipe="${r.id}">编辑配方 ↗</button></article>`).join(''):`<div class="empty-state"><h3>你的菜单还在等第一杯</h3><p>去调酒实验室，把今晚的某种心情留在杯底。</p><button class="primary-button" data-view="lab" style="margin-top:20px">开始调制 →</button></div>`; $$('.menu-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.menuFilter===filter)); }
  function renderJournal(){ $('#journal-total').textContent=state.logs.length; $('#log-badge').textContent=state.logs.length; const list=$('#journal-list'); const entries=state.logs.length?state.logs:[{date:'还没有日期',title:'酒馆尚未开张',text:'第一位客人进门之后，这里会留下今晚的第一行字。',tag:'等待故事发生'}]; list.innerHTML=entries.slice().reverse().map(e=>`<article class="journal-entry"><time>${e.date}</time><h3>${escapeHtml(e.title)}</h3><p>${escapeHtml(e.text)}</p><span class="journal-tag">${escapeHtml(e.tag)}</span></article>`).join(''); const total=state.served; const style=total>6?['有自己的天气','你已经拥有一套只属于这里的语法']:total>2?['开始有回声','客人会记得你如何让他们坐下']:['还在长成','每一杯作品、每一次回应，都会让它更像你。']; $('#style-title').textContent=style[0];$('#style-description').textContent=style[1]; $$('.style-dots i').forEach((d,i)=>d.classList.toggle('active',i<Math.min(5,total))); }
  function saveRecipe(){ if(!state.mix.ingredients.length){notify('先放进至少一种材料，今晚才有名字。');return;} const customName=$('#recipe-name')?.value.trim()||state.mix.name; const recipe={id:`custom-${Date.now()}`,name:customName||mixTitle(),desc:`${state.mix.ingredients.map(id=>baseIngredients.find(i=>i.id===id).name).join('、')}，${techniques.find(t=>t.id===state.mix.technique).name}。一杯由你决定语气的作品。`,tags:[...new Set(state.mix.ingredients.flatMap(id=>baseIngredients.find(i=>i.id===id).tags))].slice(0,3),signature:false,color:colorForMix(),mix:{...state.mix}}; state.recipes.push(recipe);state.recipeCounter++;saveState();notify(`《${recipe.name}》已留在你的菜单里。`); renderMenu(); }
  function openService(guestId){ state.selectedGuest=guestId; state.freeMode=false; saveState(); setView('lab'); notify(`听见了 ${guest().name} 的故事，决定你想怎么回应。`); }
  function serveDrink(){ const g=guest(); if(state.freeMode){state.logs.push({date:today(),title:`自由实验 · ${mixTitle()}`,text:`没有顾客催促的夜晚，你用${state.mix.ingredients.length?state.mix.ingredients.map(id=>baseIngredients.find(i=>i.id===id).name).join('、'):'空气'}，${techniques.find(t=>t.id===state.mix.technique).name}。这杯先留给自己。`,tag:'自由模式'});saveState();renderJournal();notify('这杯先留给自己。日志里多了一行。');return;} if(!state.mix.ingredients.length){notify('还没有调制完成，先选择一些材料。');return;} openResponseModal(g); }
  function renderConversation(stage){ const draft=serviceDraft; if(!draft)return; const g=guests.find(item=>item.id===draft.guestId)||guest(); const scene=sceneFor(g); const visit=draft.visitIndex; const opening=scene.openings[visit]||scene.openings[0]; const firstChoices=conversationChoices(g); const firstText=firstChoices[draft.first]||firstChoices[0]; const reply=(scene.replies[visit]||scene.replies[0])[draft.first]||(scene.replies[visit]||scene.replies[0])[0]; const followups=scene.followups[visit]||scene.followups[0]; const secondText=followups[draft.second]||followups[0]; const ending=scene.endings[draft.second]||scene.endings[0]; let content=`<div class="conversation-kicker"><span>${scene.arc}</span><span>第 ${visit+1} 次来访 · ${stage+1} / 3</span></div><h3>${stage===0?'让这段话先坐下来':stage===1?'再陪他 / 她走一小段':'这杯可以上桌了'}</h3><div class="conversation-thread"><div class="chat-bubble guest"><span class="conversation-label">${g.name}</span>${opening}</div>`; if(stage>=1)content+=`<div class="chat-bubble player"><span class="conversation-label">你</span>${firstText}</div><div class="chat-bubble guest"><span class="conversation-label">${g.name}</span>${reply}</div>`; if(stage>=2)content+=`<div class="chat-bubble player"><span class="conversation-label">你</span>${secondText}</div><div class="chat-bubble guest closing-bubble"><span class="conversation-label">今晚留下的回声</span>${ending}</div>`; content+='</div>'; if(stage===0)content+=`<p class="conversation-prompt">不用找标准答案，先用一句正常的话陪他 / 她坐下来。</p><div class="response-list">${firstChoices.map((r,i)=>`<button class="response-button conversation-choice" data-response="${i}">${r}</button>`).join('')}</div>`; if(stage===1)content+=`<p class="conversation-prompt">${g.name}没有急着结束这段话。你想怎么接住这一句？</p><div class="response-list">${followups.map((r,i)=>`<button class="response-button conversation-choice" data-response="${i}">${r}</button>`).join('')}</div>`; if(stage===2)content+=`<div class="modal-next"><button class="primary-button" id="confirm-serve" data-fit="${draft.fit}">把这杯端上桌 <span>→</span></button></div>`; $('#modal-content').innerHTML=content; }
  function openResponseModal(g){ const chosen=state.mix.ingredients.map(id=>baseIngredients.find(i=>i.id===id)).filter(Boolean); const fit=chosen.filter(i=>i.moods.includes(g.mood)).length; serviceDraft={guestId:g.id,visitIndex:visitIndexFor(g),fit,first:null,second:null,stage:0}; renderConversation(0); $('#service-modal').classList.add('open'); }
  function advanceConversation(index){ if(!serviceDraft)return; if(serviceDraft.stage===0)serviceDraft.first=index; if(serviceDraft.stage===1)serviceDraft.second=index; serviceDraft.stage=Math.min(2,serviceDraft.stage+1); renderConversation(serviceDraft.stage); }
  function confirmServe(){ const draft=serviceDraft; if(!draft||draft.stage<2)return; const g=guests.find(item=>item.id===draft.guestId)||guest(); const scene=sceneFor(g); const visit=(state.guestVisits[g.id]||0)+1; const firstChoices=conversationChoices(g); const firstText=firstChoices[draft.first]||firstChoices[0]; const reply=(scene.replies[draft.visitIndex]||scene.replies[0])[draft.first]||(scene.replies[draft.visitIndex]||scene.replies[0])[0]; const followups=scene.followups[draft.visitIndex]||scene.followups[0]; const secondText=followups[draft.second]||followups[0]; const ending=scene.endings[draft.second]||scene.endings[0]; const fit=draft.fit; state.guestVisits[g.id]=visit;state.served++;const outcome=fit>=2?'这杯没有准确说中，却恰好给了对方一个可以停留的地方。':fit===1?'味道有一点意外，但对方没有急着放下杯子。':'这杯走向了完全不同的地方——对方笑了，说也许这正是今晚需要的偏差。';state.logs.push({date:today(),title:`${g.name} · ${currentDrinkName()}`,text:`你说：“${firstText}” ${reply} 你又${secondText} ${outcome} ${ending}`,tag:`第 ${Math.min(3,visit)} 次来访 · ${scene.arc}`});saveState();serviceDraft=null;$('#service-modal').classList.remove('open');renderGuests();renderJournal();updateSidebar();notify(`${g.name} 把这杯喝到了最后。故事往前走了一小步。`); }
  function today(){ const d=new Date(); return `${d.getFullYear()} / ${String(d.getMonth()+1).padStart(2,'0')} / ${String(d.getDate()).padStart(2,'0')}`; }
  function updateSidebar(){ $('#served-count').textContent=state.served; $('#streak-fill').style.width=`${Math.min(100,state.served*12)}%`; $('#guest-badge').textContent=guests.filter(g=>(state.guestVisits[g.id]||0)<2).length; $('#top-date').textContent=today(); }
  function bindEvents(){ document.addEventListener('click',e=>{ const view=e.target.closest('[data-view]');if(view){e.preventDefault();setView(view.dataset.view);return;} const ing=e.target.closest('[data-ingredient]');if(ing){const id=ing.dataset.ingredient;state.mix.ingredients=state.mix.ingredients.includes(id)?state.mix.ingredients.filter(x=>x!==id):[...state.mix.ingredients,id];saveState();renderLab();return;} const tech=e.target.closest('[data-technique]');if(tech){state.mix.technique=tech.dataset.technique;saveState();renderLab();return;} const glass=e.target.closest('[data-glass]');if(glass){state.mix.glass=glass.dataset.glass;saveState();renderLab();return;} const gar=e.target.closest('[data-garnish]');if(gar){state.mix.garnish=gar.dataset.garnish;saveState();renderLab();return;} const atmo=e.target.closest('[data-atmosphere]');if(atmo){state.atmosphere=atmo.dataset.atmosphere;saveState();renderAtmosphere();notify(`酒馆已切换为「${atmo.querySelector('strong').textContent}」氛围。`);return;} const guestBtn=e.target.closest('[data-guest]');if(guestBtn){state.selectedGuest=guestBtn.dataset.guest;saveState();renderGuests();return;} const start=e.target.closest('[data-start-service]');if(start){openService(start.dataset.startService);return;} const resp=e.target.closest('[data-response]');if(resp){advanceConversation(Number(resp.dataset.response));return;} const menuFilter=e.target.closest('[data-menu-filter]');if(menuFilter){state.menuFilter=menuFilter.dataset.menuFilter;saveState();renderMenu();return;} const edit=e.target.closest('[data-edit-recipe]');if(edit){const recipe=state.recipes.find(r=>r.id===edit.dataset.editRecipe);if(recipe?.mix){state.mix={...state.mix,...recipe.mix};setView('lab');notify('已载入这杯作品，可以继续修改。');}return;} if(e.target.closest('#save-recipe')){saveRecipe();return;} if(e.target.closest('#serve-drink')){serveDrink();return;} if(e.target.closest('#confirm-serve')){confirmServe();return;} if(e.target.closest('#close-modal')||e.target.id==='service-modal'){$('#service-modal').classList.remove('open');serviceDraft=null;return;} if(e.target.closest('#new-recipe')){state.mix={...defaultState.mix};setView('lab');return;} if(e.target.closest('#reset-progress')){if(confirm('确定要清除本地酒馆进度吗？')){localStorage.removeItem(STORAGE_KEY);location.reload();}return;} if(e.target.closest('#sound-toggle')){state.sound=!state.sound;saveState();notify(state.sound?'环境音提示已打开（无外部音频）':'环境音提示已关闭');} }); document.addEventListener('input',e=>{if(e.target.matches('[data-flavor]')){state.mix[e.target.dataset.flavor]=Number(e.target.value);e.target.nextElementSibling.value=`${e.target.value}%`;saveState();updatePreview();}else if(e.target.id==='recipe-name'){state.mix.name=e.target.value;saveState();updatePreview();}}); $('#free-mode-toggle').addEventListener('change',e=>{state.freeMode=e.target.checked;saveState();renderLab();}); }
  function init(){ $('#top-date').textContent=today(); renderLab();renderGuests();renderMenu();renderJournal();renderAtmosphere();updateSidebar();$('#daily-quote').textContent=quotes[new Date().getDate()%quotes.length];bindEvents();setView(state.view||'home'); }
  init();
  if ('serviceWorker' in navigator && location.protocol !== 'file:') window.addEventListener('load', () => navigator.serviceWorker.register('./sw.js').catch(() => {}));
})();
